# Don't run Azure when a branch is updated, only when a PR is updated.
# Prevents double builds when a PR is made from the main repo and not a fork.
trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - '*'

pool:
  # self-hosted agent on Windows 10 1709 environment
  # includes newer Docker engine with LCOW enabled, new build of LCOW image
  # includes Ruby 2.5, Go 1.10, Node.js 10.10, hadolint
  name: Default

variables:
  NAMESPACE: puppet

steps:
- checkout: self
  clean: true
- powershell: |
    $gemfile = Join-Path -Path (Get-Location) -ChildPath 'docker/Gemfile'
    $gempath = Join-Path -Path (Get-Location) -ChildPath 'docker/.bundle/gems'
    bundle config --local gemfile $gemfile
    bundle config --local path $gempath
    bundle install
  displayName: Fetch Dependencies
  name: fetch_deps
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Write-HostDiagnostics
  displayName: Diagnostic Host Information
  name: hostinfo
- powershell: |
    . ./docker/ci/build.ps1
    Lint-Dockerfile -Path ./docker/puppet-agent-ubuntu/Dockerfile
    Lint-Dockerfile -Path ./docker/puppet-agent-alpine/Dockerfile
  displayName: Lint Ubuntu and Alpine Dockerfiles
  name: lint_dockerfiles
- powershell: |
    . ./docker/ci/build.ps1
    Build-Container -Namespace $ENV:NAMESPACE -Base 'ubuntu'
  displayName: Build Ubuntu Agent Container
  name: build_puppetagent_ubuntu_container
- powershell: |
    . ./docker/ci/build.ps1
    Invoke-ContainerTest -Name puppet-agent-ubuntu -Namespace $ENV:NAMESPACE
  displayName: Test Puppet Agent Ubuntu
  name: test_puppet_agent_ubuntu
- task: PublishTestResults@2
  displayName: Publish Puppet Agent Ubuntu test results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'docker/TEST-*.xml'
    #mergeTestResults: false # Optional
    testRunTitle: Puppet Agent Ubuntu Test Results
- powershell: |
    . ./docker/ci/build.ps1
    Build-Container -Namespace $ENV:NAMESPACE -Base 'alpine'
  displayName: Build Alpine Agent Container
  name: build_puppetagent_alpine_container
  enabled: false
- powershell: |
    . ./docker/ci/build.ps1
    Invoke-ContainerTest -Name puppet-agent-alpine -Namespace $ENV:NAMESPACE
  displayName: Test Puppet Agent Alpine
  name: test_puppet_agent_alpine
  enabled: false
- task: PublishTestResults@2
  displayName: Publish Puppet Agent Alpine test results
  enabled: false
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'docker/TEST-*.xml'
    #mergeTestResults: false # Optional
    testRunTitle: Puppet Agent Alpine Test Results
- powershell: |
    . ./docker/ci/build.ps1
    # builds alias puppet-agent to puppet-agent-ubuntu which requires forced removal
    Clear-ContainerBuilds -Name puppet-agent-ubuntu -Force
    Clear-ContainerBuilds -Name puppet-agent-alpine
  displayName: Container Cleanup
  condition: always()
