# Don't run Azure when a branch is updated, only when a PR is updated.
# Prevents double builds when a PR is made from the main repo and not a fork.
trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - '*'

pool:
  # self-hosted agent on Windows 10 1709 environment
  # includes newer Docker engine with LCOW enabled, new build of LCOW image
  # includes Ruby 2.5, Go 1.10, Node.js 10.10, hadolint
  name: Default

variables:
  NAMESPACE: puppet
  CONTAINER_NAME: puppet-agent-ubuntu
  CONTAINER_NAME2: puppet-agent-alpine
  LINT_IGNORES: DL3008 DL3018 DL4000 DL4001 DL3028

steps:
- checkout: self
  clean: true
- powershell: |
    $gemfile = Join-Path -Path (Get-Location) -ChildPath 'docker/Gemfile'
    $gempath = Join-Path -Path (Get-Location) -ChildPath 'docker/.bundle/gems'
    bundle config --local gemfile $gemfile
    bundle config --local path $gempath
    bundle install
  displayName: Fetch Dependencies
  name: fetch_deps
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Write-HostDiagnostics
  displayName: Diagnostic Host Information
  name: hostinfo
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Lint-Dockerfile -Name $ENV:CONTAINER_NAME2 -Ignore ($ENV:LINT_IGNORES -split ' ')
  displayName: Lint $(CONTAINER_NAME2) Dockerfile
  name: lint_alpine_dockerfile
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Lint-Dockerfile -Name $ENV:CONTAINER_NAME -Ignore ($ENV:LINT_IGNORES -split ' ')
  displayName: Lint $(CONTAINER_NAME) Dockerfile
  name: lint_dockerfile
- powershell: |
    . ./docker/ci/build.ps1
    Build-Container -Namespace $ENV:NAMESPACE -Base 'ubuntu'
  displayName: Build $(CONTAINER_NAME) Container
  name: build_container
- powershell: |
    . ./docker/ci/build.ps1
    Invoke-ContainerTest -Name $ENV:CONTAINER_NAME -Namespace $ENV:NAMESPACE
  displayName: Test $(CONTAINER_NAME)
  name: test_container
- task: PublishTestResults@2
  displayName: Publish $(CONTAINER_NAME) test results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'docker/TEST-*.xml'
    #mergeTestResults: false # Optional
    testRunTitle: $(CONTAINER_NAME) Test Results
- powershell: |
    . ./docker/ci/build.ps1
    Build-Container -Namespace $ENV:NAMESPACE -Base 'alpine'
  displayName: Build $(CONTAINER_NAME2) Container
  name: build_alpine_container
  enabled: false
- powershell: |
    . ./docker/ci/build.ps1
    Invoke-ContainerTest -Name $ENV:CONTAINER_NAME2 -Namespace $ENV:NAMESPACE
  displayName: Test $(CONTAINER_NAME2)
  name: test_alpine_container
  enabled: false
- task: PublishTestResults@2
  displayName: Publish $(CONTAINER_NAME2) test results
  enabled: false
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'docker/TEST-*.xml'
    #mergeTestResults: false # Optional
    testRunTitle: $(CONTAINER_NAME2) Test Results
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    # builds alias puppet-agent to puppet-agent-ubuntu which requires forced removal
    Clear-BuildState -Name $ENV:CONTAINER_NAME -Force
    Clear-BuildState -Name $ENV:CONTAINER_NAME2
  displayName: Container Cleanup
  condition: always()
